title:            San Mateo Park 4-H Club
tagline:          'A 4-H youth development club for ages 5-18 in the San Mateo area'
description:      'Innehåll på 4H'
url:              https://SanMateoPark4H.github.io
baseurl:          /

author:  
name:           'San Mateo Park 4-H'
url:            https://SanMateoPark4H.github.io

sidebar:
  title: 'San Mateo Park 4-H'
  image: https://SanMateoPark4H.github.io/2lsyor.jpg
  image_alt: 'branding requirements are complex...'
  

theme: jekyll-theme-minimal