title:            'San&nbsp;Mateo&nbsp;Park&nbsp;4‑H'
tagline:          'A 4-H youth development club for ages 5-18 in the San Mateo area'
description:      'A 4-H youth development club for ages 5-18 in the San Mateo area'
url:              https://SanMateoPark4H.github.io
logo:             https://SanMateoPark4H.github.io/2lsyor.jpg
baseurl:          /
site.github.is_user_page: false
github.is_user_page: false
is_user_page: false

  

theme: jekyll-theme-minimal
